# Generated by Django 4.2.2 on 2023-06-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='voice',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Voice'),
        ),
    ]
