# Generated by Django 4.2.2 on 2023-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='INN',
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='inn'),
        ),
    ]
