# Generated by Django 4.2.2 on 2023-06-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0002_remove_user_inn_user_inn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Worker',
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
    ]
