# Generated by Django 4.2.2 on 2023-06-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ElectionType',
                'verbose_name_plural': 'ElectionTypes',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Image')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start_Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electiontype', verbose_name='Election Type')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
            },
        ),
    ]
