# Generated by Django 4.2.2 on 2023-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='electiontype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
