# Generated by Django 4.2.2 on 2023-06-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizen',
            options={'verbose_name': 'Citizen', 'verbose_name_plural': 'Citizens'},
        ),
        migrations.AlterModelOptions(
            name='referendum',
            options={'verbose_name': 'Referendum', 'verbose_name_plural': 'Referendums'},
        ),
    ]
